Metrics/LineLength:
  Max: 160

Style/ClassAndModuleChildren:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
